CREATE TABLE public.productos (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	activo bool NOT NULL,
	descripcion varchar(255) NOT NULL,
	nombre varchar(255) NOT NULL,
	precio float8 NOT NULL,
	imagen_path varchar(350) NULL,
	CONSTRAINT productos_pkey PRIMARY KEY (id)
);

INSERT INTO public.productos
(activo, descripcion, nombre, precio, imagen_path)
VALUES( true, 'productos uno', 'uno', 16000.0, NULL);
INSERT INTO public.productos
( activo, descripcion, nombre, precio, imagen_path)
VALUES( true, 'producto dos', 'dos', 16000.0, NULL);
INSERT INTO public.productos
( activo, descripcion, nombre, precio, imagen_path)
VALUES( true, 'producto tres', 'tres', 16000.0, NULL);
INSERT INTO public.productos
(activo, descripcion, nombre, precio, imagen_path)
VALUES(true, 'caja box', 'caja', 250000.0, 'C:\Users\larape\Documents\uploads\01477061-bd96-42e6-bfbd-d54c226a83f4.png');